name: cloudbuild

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
  
env:
  PROJECT_ID: clean-mason-391409 # TODO: update Google Cloud project id
  SERVICE: pochost2 # TODO: update Cloud Run service name
  REGION: europe-west2
  SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
  SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}

jobs:
  build:
    # Allow the job to fetch a GitHub ID token
    permissions:
      contents: 'read'
      id-token: 'write'
      
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/1366473574/locations/global/workloadIdentityPools/githubactionspool/providers/github'
          service_account: 'terraform-sa@clean-mason-391409.iam.gserviceaccount.com'
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and Push Docker Image
        run: |
          gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }} ./ --project ${{ env.PROJECT_ID }}
          
      - name: Run SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ env.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION: ${{ env.SONAR_ORGANIZATION }}
        with:
          extraProperties: |
            sonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            sonar.organization=${{ env.SONAR_ORGANIZATION }}
            sonar.links.homepage=https://sonarcloud.io/project/overview?id=${{ env.SONAR_PROJECT_KEY }}
          
      - name: Run SonarLint
        run: sonarlint
      
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          image: gcr.io/${{ env.PROJECT_ID }}/pochost2
          service: pochost2
          region: europe-west2
          platform: managed
          # Add any additional flags or configurations as needed
