name: cloudbuild

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

env:
  PROJECT_ID: clean-mason-391409
  SERVICE: pochost2
  REGION: europe-west2
  SONAR_PROJECT_KEY: poc-ikea_pocapp2
  SONAR_ORGANIZATION: poc-ikea

# Use "extends" to include separate YAML files for each job
extends:
  - feature.yaml
  - pr-event.yaml
  - pr-merge.yaml

jobs:
  eslint_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add the necessary steps for ESLint job
      - name: Install dependencies
        run: npm ci
        # ... other dependency setup steps ...

      - name: Run lint
        run: |
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7
          npx eslint .
            --config .eslintrc.js
            --ext .js,.jsx,.ts,.tsx
            --format @microsoft/eslint-formatter-sarif
            --output-file eslint_report.json
        continue-on-error: true  # Continue the build even on ESLint errors

      - name: Upload ESLint report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ESLint Report
          path: eslint_report.json

  sonarcloud_scan_job:
    runs-on: ubuntu-latest
    needs: eslint_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add the necessary steps for SonarCloud Scan job
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.9.1
        with:
          projectBaseDir: src
          args: >
            -Dsonar.organization=poc-ikea
            -Dsonar.projectKey=poc-ikea_pocapp2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_deploy_job:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    needs:
      - sonarcloud_scan_job
      - merge_pr_job  # This job needs the Merge PR job to be completed before it runs
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add the necessary steps for Build and Deploy job
      - name: Install dependencies
        run: npm ci
        # ... other dependency setup steps ...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        run: |
          gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }} ./ --project ${{ env.PROJECT_ID }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          image: gcr.io/${{ env.PROJECT_ID }}/pochost2
          service: pochost2
          region: europe-west2
          platform: managed
          # Add any additional flags or configurations as needed
